//! Policy-related request / response types.
//!
//! These types define the HTTP contract for the policy CRUD API.

use serde::{Deserialize, Serialize};
use tabled::Tabled;
// ── Validation constants ──

/// Maximum length of a policy ID (UUID v4: 36 chars).
pub const POLICY_ID_MAX_LEN: u64 = 36;

/// Maximum number of policy IDs accepted by `DELETE /rbs/v0/resource/policy?ids=...`.
pub const POLICY_BATCH_DELETE_MAX_IDS: usize = 10;

/// Maximum length of the comma-separated `ids` query parameter.
pub const POLICY_IDS_QUERY_MAX_LEN: u64 = 4096;

/// Maximum length of a policy name.
pub const POLICY_NAME_MAX_LEN: u64 = 255;

/// Characters forbidden in policy names.
pub const POLICY_NAME_BLACKLIST: &[char] = &['<', '>', '"', '\'', '&', '|', '\\', '/', '*', '?', '`'];

/// Allowed content types for policy content.
pub const POLICY_CONTENT_TYPE_WHITELIST: &[&str] = &["base64"];

// ── Request / response types ──

/// Policy create request body.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema, validator::Validate)]
#[serde(rename_all = "snake_case")]
pub struct CreatePolicyRequest {
    /// Policy name, unique per user (1-255 chars; `<>\"'&|\\/*?` and backtick are forbidden).
    #[validate(length(min = 1, max = POLICY_NAME_MAX_LEN), custom(function = "validate_policy_name"))]
    #[schema(min_length = 1, max_length = 255, pattern = "^[^<>\"'&|\\\\/*?`]*$")]
    pub name: String,

    /// Encoding of `content`; only `base64` is supported.
    #[validate(custom(function = "validate_content_type"))]
    #[schema(pattern = "^base64$")]
    pub content_type: String,

    /// Base64-encoded Rego policy text; must decode to valid UTF-8 within the configured size limit.
    #[validate(length(min = 1))]
    #[schema(min_length = 1)]
    pub content: String,
}

/// Policy update request body. All fields are required (full replacement).
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema, validator::Validate)]
#[serde(rename_all = "snake_case")]
pub struct UpdatePolicyRequest {
    /// New policy name, unique per user (1-255 chars; `<>\"'&|\\/*?` and backtick are forbidden).
    #[validate(length(min = 1, max = POLICY_NAME_MAX_LEN), custom(function = "validate_policy_name"))]
    #[schema(min_length = 1, max_length = 255, pattern = "^[^<>\"'&|\\\\/*?`]*$")]
    pub name: String,

    /// New encoding of `content`; only `base64` is supported.
    #[validate(custom(function = "validate_content_type"))]
    #[schema(pattern = "^base64$")]
    pub content_type: String,

    /// New base64-encoded Rego policy text; must decode to valid UTF-8 within the configured size limit.
    #[validate(length(min = 1))]
    #[schema(min_length = 1)]
    pub content: String,
}

/// Policy response returned to callers.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema, Tabled)]
#[serde(rename_all = "snake_case")]
pub struct PolicyResponse {
    /// Policy ID (UUID v4), generated by RBS.
    pub policy_id: String,
    /// Policy name, unique per user.
    pub policy_name: String,
    /// Monotonic version: starts at 1 and increments on every update (optimistic-lock token).
    pub policy_version: i32,
    /// Encoding of the stored policy content (always `base64`).
    pub content_type: String,
    /// Creation time (RFC 3339).
    pub created_at: String,
    /// Last update time (RFC 3339).
    pub updated_at: String,
    /// URIs of resources bound to this policy; only returned by single-policy GET (omitted elsewhere).
    #[tabled(skip)]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub applied_resources: Option<Vec<String>>,
}

/// Policy list response.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub struct PolicyListResponse {
    /// Current page of policies.
    pub items: Vec<PolicyResponse>,
    /// Total matching policies (not only this page).
    pub total_count: i64,
    /// Effective page size (mirrors the request `limit`).
    pub limit: i64,
    /// Effective page offset (mirrors the request `offset`).
    pub offset: i64,
}

/// Query parameters for GET /rbs/v0/resource/policy.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::IntoParams, validator::Validate)]
#[serde(rename_all = "snake_case")]
#[into_params(parameter_in = Query)]
pub struct PolicyListQuery {
    /// Comma-separated policy IDs (UUIDs); when present, only these are returned and pagination is ignored.
    #[validate(length(min = 1, max = POLICY_IDS_QUERY_MAX_LEN))]
    #[param(min_length = 1, max_length = 4096)]
    pub ids: Option<String>,

    /// Page size (1..100, default 10).
    #[validate(range(min = 1, max = 100))]
    #[param(minimum = 1, maximum = 100)]
    pub limit: Option<i64>,

    /// Offset (0..100000, default 0).
    #[validate(range(min = 0, max = 100_000))]
    #[param(minimum = 0, maximum = 100_000)]
    pub offset: Option<i64>,
}

/// Query parameters for DELETE /rbs/v0/resource/policy.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::IntoParams)]
#[serde(rename_all = "snake_case")]
pub struct BatchDeleteQuery {
    /// Comma-separated policy IDs to delete (maximum 10).
    pub ids: String,
}

// ── Custom validators ──

fn validate_policy_name(name: &str) -> Result<(), validator::ValidationError> {
    if let Some(c) = name.chars().find(|c| POLICY_NAME_BLACKLIST.contains(c)) {
        let mut err = validator::ValidationError::new("invalid_policy_name");
        err.message = Some(format!("policy name contains forbidden character: '{}'", c).into());
        return Err(err);
    }
    Ok(())
}

fn validate_content_type(content_type: &str) -> Result<(), validator::ValidationError> {
    if !POLICY_CONTENT_TYPE_WHITELIST.contains(&content_type) {
        let mut err = validator::ValidationError::new("invalid_content_type");
        err.message = Some(format!("content_type must be one of: {}", POLICY_CONTENT_TYPE_WHITELIST.join(", ")).into());
        return Err(err);
    }
    Ok(())
}

/// Validate a policy_id path parameter.
/// Checks both length (1..36) and UUID v4 format.
pub fn validate_policy_id(id: &str) -> Result<(), String> {
    if id.is_empty() || id.len() > POLICY_ID_MAX_LEN as usize {
        Err(format!("policy_id length must be 1..{}, got {}", POLICY_ID_MAX_LEN, id.len()))
    } else if uuid::Uuid::parse_str(id).is_err() {
        Err(format!("policy_id must be a valid UUID, got '{}'", id))
    } else {
        Ok(())
    }
}
