/* rbc.h — RBC C API. Auto-generated by cbindgen. DO NOT EDIT. */

#ifndef RBC_H
#define RBC_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

/**
 * RBC C API error codes. `RBC_ERROR_CODE_OK` is success; any other value is a failure
 * whose Rust-side Display-formatted reason is retrievable via
 * `rbc_last_error_message()` **on the same thread**.
 */
typedef enum {
  RBC_ERROR_CODE_OK = 0,
  RBC_ERROR_CODE_INVALID_ARG = 1,
  RBC_ERROR_CODE_CONFIG = 2,
  RBC_ERROR_CODE_TLS = 3,
  RBC_ERROR_CODE_PROVIDER = 4,
  RBC_ERROR_CODE_KEYGEN = 5,
  RBC_ERROR_CODE_EVIDENCE = 6,
  RBC_ERROR_CODE_NETWORK = 7,
  RBC_ERROR_CODE_TIMEOUT = 8,
  RBC_ERROR_CODE_AUTH = 9,
  RBC_ERROR_CODE_POLICY_DENIED = 10,
  RBC_ERROR_CODE_RESOURCE_NOT_FOUND = 11,
  RBC_ERROR_CODE_ATTEST = 12,
  RBC_ERROR_CODE_SERVER = 13,
  RBC_ERROR_CODE_ENCRYPT = 14,
  RBC_ERROR_CODE_DECRYPT = 15,
  RBC_ERROR_CODE_JSON = 16,
  RBC_ERROR_CODE_INTERNAL = 17,
} RbcErrorCode;

typedef struct RbcClient RbcClient;

typedef struct RbcResource RbcResource;

typedef struct RbcSession RbcSession;

/**
 * FFI safety contract:
 *
 * - Handles are opaque RBC-owned pointers. Do not dereference, stack-allocate,
 *   copy, or cast between RbcClient, RbcSession, and RbcResource.
 * - Handles are not thread-safe. Use each handle only on the thread that
 *   created it, and do not use a handle concurrently from multiple threads.
 * - Release each non-NULL handle exactly once with its matching free function:
 *   RbcClientFree for RbcClient, RbcSessionFree for RbcSession, and
 *   RbcResourceFree for RbcResource.
 * - After a free call returns, the handle and all borrowed pointers obtained
 *   from it are invalid and must not be used again.
 * - Passing a pointer not returned by RBC, freeing a handle twice, freeing it
 *   with the wrong function, or using it after free is undefined behavior.
 */

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Free a nul-terminated string returned by an RBC function. The pointer must be
 * an unmodified value returned through an RBC `char **` out-parameter and must
 * be freed exactly once.
 */
void RbcStringFree(char *s);

/**
 * Free a byte buffer returned by an RBC function. `len` MUST be the value
 * the producing call wrote into its `*out_len` parameter. The pointer must be
 * an unmodified value returned through an RBC `uint8_t **` out-parameter and
 * must be freed exactly once.
 */
void RbcBufferFree(uint8_t *buf, size_t len);

/**
 * Create a client from a YAML config file on disk.
 */
RbcErrorCode RbcClientNewFromFile(const char *config_path, RbcClient **out_client);

/**
 * Create a client from an in-memory YAML string.
 */
RbcErrorCode RbcClientNewFromYaml(const char *yaml, RbcClient **out_client);

/**
 * Destroy a client handle. The handle must have been returned by RBC and must
 * not be used after this call. Freeing the same handle twice is undefined
 * behavior.
 */
void RbcClientFree(RbcClient *client);

/**
 * Fetch an authentication challenge. On success `*out_nonce` is a newly
 * allocated nul-terminated string owned by the caller; free with
 * `RbcStringFree`.
 */
RbcErrorCode RbcGetAuthChallenge(RbcClient *client, char **out_nonce);

/**
 * Return a pointer to the last error message set on the **current thread**, or
 * NULL if no error has been recorded since the last `rbc_last_error_clear` call.
 *
 * The returned pointer is valid until the next RBC API call on the same thread
 * (which may overwrite it) or the next `rbc_last_error_clear`. The caller MUST
 * NOT free it.
 */
const char *RbcLastErrorMessage(void);

/**
 * Clear the last error on the current thread.
 */
void RbcLastErrorClear(void);

/**
 * Borrow the URI. Valid until `RbcResourceFree`.
 */
const char *RbcResourceGetUri(const RbcResource *resource);

/**
 * Borrow the content-type (may be NULL). Valid until `RbcResourceFree`.
 */
const char *RbcResourceGetContentType(const RbcResource *resource);

/**
 * Borrow the raw content bytes. Writes the length into `*out_len`. Valid
 * until `RbcResourceFree`.
 */
const uint8_t *RbcResourceGetContent(const RbcResource *resource, size_t *out_len);

/**
 * Destroy a resource handle (invalidates all borrowed pointers obtained
 * from accessors). The handle must have been returned by RBC and must not be
 * used after this call. Freeing the same handle twice is undefined behavior.
 */
void RbcResourceFree(RbcResource *resource);

/**
 * Begin a new session. `attester_data_json` may be NULL. If non-NULL it must
 * be a JSON object matching `AttesterData` (per `rbs_api.yaml`); if its
 * `runtime_data.tee-pubkey` is present the caller is responsible for the
 * matching private key (pass it to `RbcSessionDecryptContent`).
 */
RbcErrorCode RbcSessionNew(RbcClient *client,
                           const char *attester_data_json,
                           RbcSession **out_session);

/**
 * Free a session. The embedded ephemeral key is zeroized on drop. The handle
 * must have been returned by RBC and must not be used after this call. Freeing
 * the same handle twice is undefined behavior.
 */
void RbcSessionFree(RbcSession *session);

/**
 * Collect evidence for `nonce`. On success `*out_evidence_json` is a newly
 * allocated JSON-encoded nul-terminated string owned by the caller.
 */
RbcErrorCode RbcSessionCollectEvidence(RbcSession *session,
                                       const char *nonce,
                                       char **out_evidence_json);

/**
 * Exchange evidence for an attest token. `evidence_json` may be NULL (in
 * which case the session's TokenProvider must be able to produce a token
 * without one). On success `*out_token` is a newly allocated nul-terminated
 * string owned by the caller.
 */
RbcErrorCode RbcSessionAttest(RbcSession *session, const char *evidence_json, char **out_token);

/**
 * Fetch a resource using a previously-obtained attest token.
 */
RbcErrorCode RbcSessionGetResourceByToken(RbcSession *session,
                                          const char *uri,
                                          const char *token,
                                          RbcResource **out_resource);

/**
 * Fetch a resource using an evidence bundle (pull-by-evidence mode).
 */
RbcErrorCode RbcSessionGetResourceByEvidence(RbcSession *session,
                                             const char *uri,
                                             const char *evidence_json,
                                             RbcResource **out_resource);

/**
 * Decrypt a JWE token using the session's key.
 *
 * If `private_key_pem` is non-NULL it is always used, regardless of whether
 * the session holds an ephemeral key. This allows stateless callers (e.g. a
 * CLI) to supply a long-lived private key without requiring the same session
 * that collected evidence. Pass NULL to fall back to the session's ephemeral
 * key.
 *
 * On success `*out_plaintext` is a newly allocated buffer of `*out_len` bytes
 * owned by the caller; release with `RbcBufferFree(buf, len)`.
 * `passphrase` / `passphrase_len` — pass a non-NULL pointer and byte length when
 * `private_key_pem` is encrypted; pass NULL / 0 otherwise. Caller is responsible
 * for zeroizing the passphrase buffer after this call returns.
 */
RbcErrorCode RbcSessionDecryptContent(RbcSession *session,
                                      const char *jwe,
                                      const char *private_key_pem,
                                      const uint8_t *passphrase,
                                      size_t passphrase_len,
                                      uint8_t **out_plaintext,
                                      size_t *out_len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RBC_H */
